# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 20:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_date',
            field=models.DateTimeField(default=datetime.date(1995, 11, 17), verbose_name="note's date"),
        ),
        migrations.AddField(
            model_name='note',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
