# Generated by Django 2.0.2 on 2018-02-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20170821_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_value',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
